//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP8.Crebits.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP8.Crebits.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string AdsCaption {
            get {
                return ResourceManager.GetString("AdsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxx@xxx.com.
        /// </summary>
        public static string AuthorEmail {
            get {
                return ResourceManager.GetString("AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string ContinueQuestion {
            get {
                return ResourceManager.GetString("ContinueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debits.
        /// </summary>
        public static string Debits {
            get {
                return ResourceManager.GetString("Debits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteCategoryMessage {
            get {
                return ResourceManager.GetString("DeleteCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos; ({1})?.
        /// </summary>
        public static string DeleteOperationMessage {
            get {
                return ResourceManager.GetString("DeleteOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linda Gomez.
        /// </summary>
        public static string Designer {
            get {
                return ResourceManager.GetString("Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled?.
        /// </summary>
        public static string DisabledQuestion {
            get {
                return ResourceManager.GetString("DisabledQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display decimal digits.
        /// </summary>
        public static string DisplayDecimalDigitsOnTheLiveTile {
            get {
                return ResourceManager.GetString("DisplayDecimalDigitsOnTheLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outch!.
        /// </summary>
        public static string ErrorReportCaption {
            get {
                return ResourceManager.GetString("ErrorReportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred the last time you ran this application. Would you like to send an email to report it?.
        /// </summary>
        public static string ErrorReportMessage {
            get {
                return ResourceManager.GetString("ErrorReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address to which you want the reports sent (optional).
        /// </summary>
        public static string ExportDataEmailOptionNote {
            get {
                return ResourceManager.GetString("ExportDataEmailOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page &gt; Application Bar &gt;.
        /// </summary>
        public static string ExportDataOptionNote {
            get {
                return ResourceManager.GetString("ExportDataOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string ExportFormat {
            get {
                return ResourceManager.GetString("ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this app, could you please take a moment to rate it? :).
        /// </summary>
        public static string FeedbackExplanation {
            get {
                return ResourceManager.GetString("FeedbackExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Tile.
        /// </summary>
        public static string LiveTile {
            get {
                return ResourceManager.GetString("LiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color (Cash &lt; Limit value).
        /// </summary>
        public static string MinCashLimitColor {
            get {
                return ResourceManager.GetString("MinCashLimitColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit value.
        /// </summary>
        public static string MinCashLimitValue {
            get {
                return ResourceManager.GetString("MinCashLimitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly?.
        /// </summary>
        public static string MonthlyQuestion {
            get {
                return ResourceManager.GetString("MonthlyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No category.
        /// </summary>
        public static string NoCategory {
            get {
                return ResourceManager.GetString("NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex, your &apos;Rent&apos; (with &apos;Monthly&apos; option).
        /// </summary>
        public static string NoCreditExample {
            get {
                return ResourceManager.GetString("NoCreditExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Debit entry using the menu at the bottom of the screen.
        /// </summary>
        public static string NoCreditExplanation {
            get {
                return ResourceManager.GetString("NoCreditExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex, your &apos;Salary&apos; (with &apos;Monthly&apos; option).
        /// </summary>
        public static string NoDebitExample {
            get {
                return ResourceManager.GetString("NoDebitExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Credit entry using the menu at the bottom of the screen.
        /// </summary>
        public static string NoDebitExplanation {
            get {
                return ResourceManager.GetString("NoDebitExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for {0}.
        /// </summary>
        public static string OverrideCaption {
            get {
                return ResourceManager.GetString("OverrideCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase me!.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete non-monthly entries.
        /// </summary>
        public static string Purge {
            get {
                return ResourceManager.GetString("Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all credits &amp; debits that are not set as monthly.
        /// </summary>
        public static string PurgeExplaination {
            get {
                return ResourceManager.GetString("PurgeExplaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete non-monthly entries?.
        /// </summary>
        public static string PurgeMessage {
            get {
                return ResourceManager.GetString("PurgeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider exporting data before executing this action.
        /// </summary>
        public static string PurgeOptionNote {
            get {
                return ResourceManager.GetString("PurgeOptionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app!.
        /// </summary>
        public static string RateThisApp {
            get {
                return ResourceManager.GetString("RateThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Back.
        /// </summary>
        public static string ShowAmounts {
            get {
                return ResourceManager.GetString("ShowAmounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph &gt;&gt;.
        /// </summary>
        public static string ShowPieGraph {
            get {
                return ResourceManager.GetString("ShowPieGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized debits ~{0}%.
        /// </summary>
        public static string UnCategorizedDebitsPercent {
            get {
                return ResourceManager.GetString("UnCategorizedDebitsPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme (needs app restart).
        /// </summary>
        public static string UseLightTheme {
            get {
                return ResourceManager.GetString("UseLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml.
        /// </summary>
        public static string Xml {
            get {
                return ResourceManager.GetString("Xml", resourceCulture);
            }
        }
    }
}
